apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portAPI }}
      targetPort: http
      protocol: TCP
      name: api
  selector:
    app: {{ .Values.servicename }}