# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

servicename: api

environment: 'kubernetes'

# environment options:
# environment: 'kubernetes'
# environment: 'openshift'

vault:
  status: 'disabled'
  kind: 'disabled'

# vault.status options:
# vault.status: 'kv_static' # use kv secrets engine for vault aware apps (app talks to the Vault API)
# vault.status: 'kv_static_injector_template_file' # use kv secrets engine for vault unaware apps (app uses reads secrets from a file on the file system)
# vault.status: 'kv_static_csi' # use kv secrets engine with the vault CSI provider (used for vault unaware apps)
# vault.status: '<any other value including disabled>' # use Hardcoded Values that appear in GitLab

# vault.kind options:
# vault.kind: 'injector' # uses the vault injector
# vault.kind: 'csi' # uses the vault CSI provider
# vault.kind: '<any other value including disabled>' will not rely on vault at all

CORS: http://127.0.0.1:8001

api:
  image:
    repository: samgabrail/schoolapp_api
    pullPolicy: Always
    tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "schoolapp"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  portFrontend: 80
  portAPI: 5000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - hostsAPI: api.schoolapp.com
      hostsFrontend: app.schoolapp.com
  tls:
    - secretNameAPI: api-schoolapp-tls
      secretNameFrontend: frontend-schoolapp-tls
      hostsAPI:
        - api.schoolapp.com
      hostsFrontend:
        - app.schoolapp.com